### PR TITLE
Fixes url for clickhouse server

### PR DESCRIPTION
**Pull request by evengar2008**
Fixes url for clickhouse server - there was a bug with duplicate URL in the query

The library was sending requests to CH server like

it's sending a request like

http://clickhouse.some/http://clickhouse.some/?database=x%60

instead of

http://clickhouse.some/?database=x%60

### CODE REVIEW

**Comment by elcamlost** [comment]
A few thought on that.

1. I'm not in favor of switching die to confess. If you need a proper stack traces in your application you should do that yourself, it is not the job of the library.
2. Did you check that this approach works correctly with the older version of clickhouse?

**Comment by evengar2008** [comment]
1. Ok, I reverted that commit then
2. Sure, it works both with v20.7.2.30, and v.23.10.5.20

**Comment by poizon** [comment]
I checked on 23.12.1 and 22.8.5 - it works.

**Comment by dmitry-novozhilov** [comment]
It works for me.

**Comment by elcamlost** [comment]
I’m planning to release the new version this weekend. Thanks for the contribution and stay tuned. ——Best regards, Ilia Rassadin.6 янв. 2024 г., в 09:23, Дмитрий Новожилов ***@***.***> написал(а):﻿
It works for me.

**Pull request merged**
